[virtualenvs]
# Create local virtualenv stored in .venv
# https://python-poetry.org/docs/configuration/#virtualenvsin-project
# poetry config virtualenvs.create true --local
# poetry config virtualenvs.in-project true --local
create = true
in-project = true