# This workflow run the script "run_this_benchmark.py"
name: Run benchmarks

on: workflow_dispatch

jobs:
  # This workflow contains a single job called "benchmarking"
  benchmarking:
    permissions:
      contents: write
  # The type of runner that the job will run on
    strategy:
      matrix:
#         os: ["ubuntu-latest", "macos-latest"]
        os: ["ubuntu-latest"]
        # python-version: ["3.7", "3.8", "3.9"]
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout project
        uses: actions/checkout@v2

      # Install python
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      # Install Poetry and the dependencies
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      
      - name: Install package
        run: poetry install
      
      # - name: Test with pytest
        # run: poetry run pytest

      - name: Run the Benchmark
        run: |
          poetry run python run_this_benchmark.py

      - name: Commit and push files
        run: |
          git config --local user.email "MeBot@github.com"
          git config --local user.name "MeBot"
          git add results --all
          git commit -m "Add changes" -a
          git push origin main
          
